apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: fargate-apps
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use NLB (Network Load Balancer) for Fargate
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80      # Port exposed outside
      targetPort: 80 # Port inside the container
  type: LoadBalancer
