apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: default
spec:
  selector:
    app: fastapi
  ports:
    - name: fastapi-port
      protocol: TCP
      port: 80  
      targetPort: 80  
  type: ClusterIP

